ALTER SESSION SET "_ORACLE_SCRIPT" = true;
/

-- 1. SPRZEDAZ.PRODUKT_CACHE
DELETE FROM SPRZEDAZ.POZYCJA_ZAMOWIENIA;
DELETE FROM SPRZEDAZ.ZAMOWIENIE;
DELETE FROM SPRZEDAZ.KLIENT;
DELETE FROM SPRZEDAZ.PRODUKT_CACHE;

INSERT INTO SPRZEDAZ.PRODUKT_CACHE (ID_PRODUKTU, NAZWA, JEDNOSTKA_MIARY, STAWKA_VAT, CENA_NETTO)
VALUES (1, 'Fasola konserwowa 400g', 'szt.', 8,  4.20);
INSERT INTO SPRZEDAZ.PRODUKT_CACHE (ID_PRODUKTU, NAZWA, JEDNOSTKA_MIARY, STAWKA_VAT, CENA_NETTO)
VALUES (2, 'Makaron swiderki 500g',  'szt.', 5,  3.10);
INSERT INTO SPRZEDAZ.PRODUKT_CACHE (ID_PRODUKTU, NAZWA, JEDNOSTKA_MIARY, STAWKA_VAT, CENA_NETTO)
VALUES (3, 'Olej rzepakowy 1l',      'szt.', 5,  8.90);
INSERT INTO SPRZEDAZ.PRODUKT_CACHE (ID_PRODUKTU, NAZWA, JEDNOSTKA_MIARY, STAWKA_VAT, CENA_NETTO)
VALUES (4, 'Pieprz czarny 100g',     'szt.', 8,  5.50);
INSERT INTO SPRZEDAZ.PRODUKT_CACHE (ID_PRODUKTU, NAZWA, JEDNOSTKA_MIARY, STAWKA_VAT, CENA_NETTO)
VALUES (5, 'Pierogi mrozone 1kg',    'szt.', 5, 11.00);

-- 2. SPRZEDAZ.KLIENT
INSERT INTO SPRZEDAZ.KLIENT (ID_KLIENTA, NAZWA, NIP, ID_SEGMENTU)
VALUES (1, 'Sklep Spozywczy Maja',      '1110000001', 1);
INSERT INTO SPRZEDAZ.KLIENT (ID_KLIENTA, NAZWA, NIP, ID_SEGMENTU)
VALUES (2, 'Restauracja Pod Lipa',      '1110000002', 2);
INSERT INTO SPRZEDAZ.KLIENT (ID_KLIENTA, NAZWA, NIP, ID_SEGMENTU)
VALUES (3, 'Stolowka Szkolna nr 5',     '1110000003', 4);

COMMIT;

-- 3. Zamowienia using PKG_SPRZEDAZ
DECLARE
    v_zam1 NUMBER;
    v_zam2 NUMBER;
    v_zam3 NUMBER;
BEGIN
    -- klient 1
    SPRZEDAZ.PKG_SPRZEDAZ.sp_zarejestruj_zamowienie(p_id_klienta => 1, p_id_zamowienia => v_zam1);
    SPRZEDAZ.PKG_SPRZEDAZ.sp_dodaj_pozycje(v_zam1, 1, 10);   -- 10 x fasola
    SPRZEDAZ.PKG_SPRZEDAZ.sp_dodaj_pozycje(v_zam1, 2, 20);   -- 20 x makaron

    -- klient 2
    SPRZEDAZ.PKG_SPRZEDAZ.sp_zarejestruj_zamowienie(p_id_klienta => 2, p_id_zamowienia => v_zam2);
    SPRZEDAZ.PKG_SPRZEDAZ.sp_dodaj_pozycje(v_zam2, 3, 5);    -- 5 x olej
    SPRZEDAZ.PKG_SPRZEDAZ.sp_dodaj_pozycje(v_zam2, 5, 8);    -- 8 x pierogi

    -- klient 3
    SPRZEDAZ.PKG_SPRZEDAZ.sp_zarejestruj_zamowienie(p_id_klienta => 3, p_id_zamowienia => v_zam3);
    SPRZEDAZ.PKG_SPRZEDAZ.sp_dodaj_pozycje(v_zam3, 4, 15);   -- 15 x pieprz

    DBMS_OUTPUT.PUT_LINE('Utworzono zamowienia: ' || v_zam1 || ', ' || v_zam2 || ', ' || v_zam3);
END;
/

COMMIT;

-- 4. ARCHIWUM
INSERT INTO ARCHIWUM.ZAMOWIENIE_ARCH
    (ID_ZAMOWIENIA, ID_KLIENTA, DATA_ZLOZENIA, DATA_ZARCHIWIZOWANIA, STATUS_KONCOWY)
VALUES
    (9001, 1, DATE '2023-02-10', DATE '2023-05-01', 'ZREALIZOWANE');

INSERT INTO ARCHIWUM.POZYCJA_ZAMOWIENIA_ARCH
    (ID_POZYCJI, ID_ZAMOWIENIA, ID_PRODUKTU, ILOSC, CENA_NETTO_ZAMROZONA, KWOTA_BRUTTO)
VALUES
    (9001, 9001, 1, 100, 4.00, 432.00);
INSERT INTO ARCHIWUM.POZYCJA_ZAMOWIENIA_ARCH
    (ID_POZYCJI, ID_ZAMOWIENIA, ID_PRODUKTU, ILOSC, CENA_NETTO_ZAMROZONA, KWOTA_BRUTTO)
VALUES
    (9002, 9001, 3, 50, 8.50, 446.25);

COMMIT;

-- 5. SELECT
SELECT * FROM SPRZEDAZ.PRODUKT_CACHE ORDER BY ID_PRODUKTU;
SELECT * FROM SPRZEDAZ.KLIENT ORDER BY ID_KLIENTA;
SELECT * FROM SPRZEDAZ.ZAMOWIENIE ORDER BY ID_ZAMOWIENIA;
SELECT * FROM SPRZEDAZ.POZYCJA_ZAMOWIENIA ORDER BY ID_ZAMOWIENIA, ID_POZYCJI;

-- (LNK_ARCHIWUM):
-- SELECT * FROM SPRZEDAZ.V_ZAMOWIENIA_PELNE ORDER BY ID_ZAMOWIENIA;

-- (SET SERVEROUTPUT ON):
-- BEGIN SPRZEDAZ.PKG_SPRZEDAZ.sp_raport_top_klienci(10); END;
