ALTER SESSION SET "_ORACLE_SCRIPT" = true;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER SPRZEDAZ CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER ARCHIWUM CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER FINANSE CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER SPRZEDAZ IDENTIFIED BY "123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ARCHIWUM IDENTIFIED BY "123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER FINANSE IDENTIFIED BY "123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

GRANT CREATE SESSION TO SPRZEDAZ;
GRANT CREATE SESSION TO ARCHIWUM;
GRANT CREATE SESSION TO FINANSE;
