-- Dropping existing tables

-- 1. SPRZEDAZ
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.POZYCJA_ZAMOWIENIA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.ZAMOWIENIE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.KLIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.SEGMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.STATUS_ZAMOWIENIA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.PRODUKT_CACHE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SPRZEDAZ.PRODUKT_CACHE_STG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. ARCHIWUM
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ARCHIWUM.POZYCJA_ZAMOWIENIA_ARCH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ARCHIWUM.ZAMOWIENIE_ARCH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 3. FINANSE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FINANSE.PLATNOSC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FINANSE.FAKTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Creating tables

-- 1. ARCHIWUM schema
CREATE TABLE ARCHIWUM.ZAMOWIENIE_ARCH (
    ID_ZAMOWIENIA        NUMBER(10) CONSTRAINT PK_ZAMOWIENIE_ARCH PRIMARY KEY,
    ID_KLIENTA           NUMBER(10) NOT NULL,
    DATA_ZLOZENIA        DATE NOT NULL,
    DATA_ZARCHIWIZOWANIA DATE DEFAULT SYSDATE NOT NULL,
    STATUS_KONCOWY       VARCHAR2(50) NOT NULL
);

CREATE TABLE ARCHIWUM.POZYCJA_ZAMOWIENIA_ARCH (
    ID_POZYCJI            NUMBER(10) CONSTRAINT PK_POZYCJA_ZAMOWIENIA_ARCH PRIMARY KEY,
    ID_ZAMOWIENIA         NUMBER(10) NOT NULL CONSTRAINT FK_POZ_ARCH_ZAM_ARCH REFERENCES ARCHIWUM.ZAMOWIENIE_ARCH(ID_ZAMOWIENIA),
    ID_PRODUKTU           NUMBER(10) NOT NULL,
    ILOSC                 NUMBER(10,3) NOT NULL,
    CENA_NETTO_ZAMROZONA  NUMBER(10,2) NOT NULL,
    KWOTA_BRUTTO          NUMBER(12,2) NOT NULL
);

-- 2. FINANSE schema
CREATE TABLE FINANSE.FAKTURA (
    ID_FAKTURY       NUMBER(10) CONSTRAINT PK_FAKTURA PRIMARY KEY,
    ID_ZAMOWIENIA    NUMBER(10) NOT NULL,
    NUMER_FAKTURY    VARCHAR2(50) NOT NULL UNIQUE,
    DATA_WYSTAWIENIA DATE DEFAULT SYSDATE NOT NULL,
    KWOTA_NETTO      NUMBER(12,2) NOT NULL,
    KWOTA_VAT        NUMBER(12,2) NOT NULL,
    KWOTA_BRUTTO     NUMBER(12,2) NOT NULL,
    STATUS           VARCHAR2(50) NOT NULL
);

CREATE TABLE FINANSE.PLATNOSC (
    ID_PLATNOSCI    NUMBER(10) CONSTRAINT PK_PLATNOSC PRIMARY KEY,
    ID_FAKTURY      NUMBER(10) NOT NULL CONSTRAINT FK_PLATNOSC_FAKTURA REFERENCES FINANSE.FAKTURA(ID_FAKTURY),
    DATA_PLATNOSCI  DATE DEFAULT SYSDATE NOT NULL,
    KWOTA           NUMBER(12,2) NOT NULL,
    FORMA_PLATNOSCI VARCHAR2(50) NOT NULL
);

-- 3. SPRZEDAZ schema
CREATE TABLE SPRZEDAZ.SEGMENT (
    ID_SEGMENTU NUMBER(10) CONSTRAINT PK_SEGMENT PRIMARY KEY,
    NAZWA       VARCHAR2(50) NOT NULL
);

CREATE TABLE SPRZEDAZ.KLIENT (
    ID_KLIENTA  NUMBER(10) CONSTRAINT PK_KLIENT PRIMARY KEY,
    NAZWA       VARCHAR2(150) NOT NULL,
    NIP         VARCHAR2(20),
    ID_SEGMENTU NUMBER(10) CONSTRAINT FK_KLIENT_SEGMENT REFERENCES SPRZEDAZ.SEGMENT(ID_SEGMENTU)
);

CREATE TABLE SPRZEDAZ.STATUS_ZAMOWIENIA (
    ID_STATUSU NUMBER(10) CONSTRAINT PK_STATUS_ZAMOWIENIA PRIMARY KEY,
    NAZWA      VARCHAR2(50) NOT NULL
);

CREATE TABLE SPRZEDAZ.ZAMOWIENIE (
    ID_ZAMOWIENIA NUMBER(10) CONSTRAINT PK_ZAMOWIENIE PRIMARY KEY,
    ID_KLIENTA    NUMBER(10) NOT NULL CONSTRAINT FK_ZAMOWIENIE_KLIENT REFERENCES SPRZEDAZ.KLIENT(ID_KLIENTA),
    ID_STATUSU    NUMBER(10) NOT NULL CONSTRAINT FK_ZAMOWIENIE_STATUS REFERENCES SPRZEDAZ.STATUS_ZAMOWIENIA(ID_STATUSU),
    DATA_ZLOZENIA DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SPRZEDAZ.PRODUKT_CACHE (
    ID_PRODUKTU         NUMBER(10) CONSTRAINT PK_PRODUKT_CACHE PRIMARY KEY,
    NAZWA               VARCHAR2(200) NOT NULL,
    JEDNOSTKA_MIARY     VARCHAR2(20) NOT NULL,
    STAWKA_VAT          NUMBER(5,2) NOT NULL,
    CENA_NETTO          NUMBER(10,2) NOT NULL,
    DATA_SYNCHRONIZACJI DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SPRZEDAZ.POZYCJA_ZAMOWIENIA (
    ID_POZYCJI           NUMBER(10) CONSTRAINT PK_POZYCJA_ZAMOWIENIA PRIMARY KEY,
    ID_ZAMOWIENIA        NUMBER(10) NOT NULL CONSTRAINT FK_POZYCJA_ZAMOWIENIE REFERENCES SPRZEDAZ.ZAMOWIENIE(ID_ZAMOWIENIA),
    ID_PRODUKTU          NUMBER(10) NOT NULL CONSTRAINT FK_POZYCJA_PRODUKT REFERENCES SPRZEDAZ.PRODUKT_CACHE(ID_PRODUKTU),
    ILOSC                NUMBER(10,3) NOT NULL,
    CENA_NETTO_ZAMROZONA NUMBER(10,2) NOT NULL,
    STAWKA_VAT_ZAMROZONA NUMBER(5,2) NOT NULL,
    KWOTA_BRUTTO         NUMBER(12,2) NOT NULL
);

CREATE TABLE SPRZEDAZ.PRODUKT_CACHE_STG (
    ID_PRODUKTU     NUMBER(10) CONSTRAINT PK_PRODUKT_CACHE_STG PRIMARY KEY,
    NAZWA           VARCHAR2(200) NOT NULL,
    JEDNOSTKA_MIARY VARCHAR2(20) NOT NULL,
    STAWKA_VAT      NUMBER(5,2) NOT NULL,
    CENA_NETTO      NUMBER(10,2) NOT NULL
);
