ALTER SESSION SET "_ORACLE_SCRIPT" = true;
/

-- Dropping all roles

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE rola_sprzedaz';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE rola_archiwum_ro';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE rola_finanse';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Creating roles

CREATE ROLE rola_sprzedaz;
CREATE ROLE rola_archiwum_ro;
CREATE ROLE rola_finanse;
/

-- Assigning privilages to rola_sprzedaz
GRANT SELECT ON SPRZEDAZ.STATUS_ZAMOWIENIA TO rola_sprzedaz;
GRANT SELECT ON SPRZEDAZ.SEGMENT TO rola_sprzedaz;

GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.PRODUKT_CACHE TO rola_sprzedaz;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.PRODUKT_CACHE_STG TO rola_sprzedaz;

GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.ZAMOWIENIE TO rola_sprzedaz;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.POZYCJA_ZAMOWIENIA TO rola_sprzedaz;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.KLIENT TO rola_sprzedaz;

-- Assigning privilages to rola_archiwum_ro
GRANT SELECT ON ARCHIWUM.ZAMOWIENIE_ARCH TO rola_archiwum_ro;
GRANT SELECT ON ARCHIWUM.POZYCJA_ZAMOWIENIA_ARCH TO rola_archiwum_ro;

-- Assigning privilages to rola_finanse
GRANT SELECT, INSERT, UPDATE, DELETE ON FINANSE.PLATNOSC TO rola_finanse;
GRANT SELECT, INSERT, UPDATE, DELETE ON FINANSE.FAKTURA TO rola_finanse;
