ALTER SESSION SET "_ORACLE_SCRIPT" = true;
/

-- Dropping all users

BEGIN
    EXECUTE IMMEDIATE 'DROP USER SPRZEDAZ_USER CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER FINANSE_USER CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create users

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER SPRZEDAZ_USER IDENTIFIED BY "123"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER FINANSE_USER IDENTIFIED BY "123"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

GRANT CREATE SESSION TO SPRZEDAZ_USER;
GRANT CREATE SESSION TO FINANSE_USER;

-- Grant appropiate roles to user SPRZEDAZ
GRANT rola_sprzedaz TO SPRZEDAZ_USER;
GRANT rola_archiwum_ro TO SPRZEDAZ_USER;

-- Grant appropiate roles to user FINANSE
GRANT rola_finanse TO FINANSE_USER;

-- Granty bezposrednio na uzytkownika: przez linked server (OLE DB) Oracle
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.PRODUKT_CACHE TO SPRZEDAZ_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.PRODUKT_CACHE_STG TO SPRZEDAZ_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.ZAMOWIENIE TO SPRZEDAZ_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SPRZEDAZ.POZYCJA_ZAMOWIENIA TO SPRZEDAZ_USER;
GRANT SELECT ON SPRZEDAZ.KLIENT TO SPRZEDAZ_USER;
GRANT SELECT ON SPRZEDAZ.SEGMENT TO SPRZEDAZ_USER;
GRANT SELECT ON SPRZEDAZ.STATUS_ZAMOWIENIA TO SPRZEDAZ_USER;
-- GRANT EXECUTE na PKG_SPRZEDAZ jest w 11_create_packages.sql (pakiet musi juz istniec)
