-- Dropping existing sequences

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SPRZEDAZ.SEQ_ZAMOWIENIE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SPRZEDAZ.SEQ_POZYCJA_ZAMOWIENIA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE FINANSE.SEQ_FAKTURA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE FINANSE.SEQ_PLATNOSC';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SPRZEDAZ.SEQ_KLIENT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Creating sequences

CREATE SEQUENCE SPRZEDAZ.SEQ_ZAMOWIENIE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SPRZEDAZ.SEQ_POZYCJA_ZAMOWIENIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FINANSE.SEQ_FAKTURA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FINANSE.SEQ_PLATNOSC START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SPRZEDAZ.SEQ_KLIENT START WITH 1 INCREMENT BY 1 NOCACHE;
