GRANT CREATE PUBLIC DATABASE LINK TO ARCHIWUM;
GRANT CREATE DATABASE LINK TO FINANSE_USER;

BEGIN
    EXECUTE IMMEDIATE 'DROP PUBLIC DATABASE LINK LNK_ARCHIWUM';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE PUBLIC DATABASE LINK LNK_ARCHIWUM
CONNECT TO ARCHIWUM IDENTIFIED BY "123"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=pdb)))'; -- XE -> pdb
