-- Execute as a FINANSE_USER
BEGIN
    EXECUTE IMMEDIATE 'DROP DATABASE LINK LNK_FINANSE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE DATABASE LINK LNK_FINANSE
CONNECT TO FINANSE IDENTIFIED BY "123"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=pdb)))'; -- XE -> pdb
