CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.ZAMOWIENIE FOR SPRZEDAZ.ZAMOWIENIE;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.POZYCJA_ZAMOWIENIA FOR SPRZEDAZ.POZYCJA_ZAMOWIENIA;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.KLIENT FOR SPRZEDAZ.KLIENT;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.SEGMENT FOR SPRZEDAZ.SEGMENT;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.STATUS_ZAMOWIENIA FOR SPRZEDAZ.STATUS_ZAMOWIENIA;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.PRODUKT_CACHE FOR SPRZEDAZ.PRODUKT_CACHE;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.PRODUKT_CACHE_STG FOR SPRZEDAZ.PRODUKT_CACHE_STG;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.V_ZAMOWIENIA_PELNE FOR SPRZEDAZ.V_ZAMOWIENIA_PELNE;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.V_POZYCJE_PELNE FOR SPRZEDAZ.V_POZYCJE_PELNE;
CREATE OR REPLACE SYNONYM SPRZEDAZ_USER.PKG_SPRZEDAZ FOR SPRZEDAZ.PKG_SPRZEDAZ;

CREATE OR REPLACE SYNONYM FINANSE_USER.FAKTURA FOR FINANSE.FAKTURA;
CREATE OR REPLACE SYNONYM FINANSE_USER.PLATNOSC FOR FINANSE.PLATNOSC;
