CREATE OR REPLACE VIEW SPRZEDAZ.V_ZAMOWIENIA_PELNE AS
SELECT
    z.ID_ZAMOWIENIA,
    z.ID_KLIENTA,
    z.DATA_ZLOZENIA,
    'ZAMOWIENIE' AS ZRODLO,
    sz.NAZWA AS STATUS
FROM SPRZEDAZ.ZAMOWIENIE z
JOIN SPRZEDAZ.STATUS_ZAMOWIENIA sz ON z.ID_STATUSU = sz.ID_STATUSU
UNION ALL
SELECT
    ID_ZAMOWIENIA,
    ID_KLIENTA,
    DATA_ZLOZENIA,
    'ARCHIWUM' AS ZRODLO,
    STATUS_KONCOWY AS STATUS
FROM ARCHIWUM.ZAMOWIENIE_ARCH@LNK_ARCHIWUM;
/

CREATE OR REPLACE VIEW SPRZEDAZ.V_POZYCJE_PELNE AS
SELECT
    ID_POZYCJI,
    ID_ZAMOWIENIA,
    ID_PRODUKTU,
    ILOSC,
    CENA_NETTO_ZAMROZONA,
    STAWKA_VAT_ZAMROZONA,
    KWOTA_BRUTTO,
    'POZYCJA ZAMOWIENIA' AS ZRODLO
FROM SPRZEDAZ.POZYCJA_ZAMOWIENIA
UNION ALL
SELECT
    ID_POZYCJI,
    ID_ZAMOWIENIA,
    ID_PRODUKTU,
    ILOSC,
    CENA_NETTO_ZAMROZONA,
    CAST(NULL AS NUMBER(5,2)) AS STAWKA_VAT_ZAMROZONA,
    KWOTA_BRUTTO,
    'ARCHIWUM' AS ZRODLO
FROM ARCHIWUM.POZYCJA_ZAMOWIENIA_ARCH@LNK_ARCHIWUM;
/

-- Grant privilages to use these views to rola_sprzedaz
GRANT SELECT ON SPRZEDAZ.V_ZAMOWIENIA_PELNE TO rola_sprzedaz;
GRANT SELECT ON SPRZEDAZ.V_POZYCJE_PELNE TO rola_sprzedaz;
