/*DROP TABLE Nowa
CREATE TABLE Nowa
(nr1 int,
--UNIQUE,
--PRIMARY KEY,
nr2 int,
--CONSTRAINT pk PRIMARY KEY(nr1, nr2)
CONSTRAINT pk UNIQUE(nr1, nr2)
)

INSERT INTO Nowa VALUES (1, 1)
INSERT INTO Nowa VALUES (1, 2)
INSERT INTO Nowa VALUES (2, 1)
INSERT INTO Nowa VALUES (2, 2)
INSERT INTO Nowa VALUES (1, 2)
INSERT INTO Nowa(nr1) VALUES (3)
INSERT INTO Nowa(nr2) VALUES (4)
INSERT INTO Nowa(nr2) VALUES (5)

SELECT * FROM Nowa*/

DROP TABLE Nowa
CREATE TABLE Nowa
(NowaId int IDENTITY(2, -3) PRIMARY KEY,
nr1 int NOT NULL UNIQUE,
nr2 int NOT NULL UNIQUE
)

INSERT INTO Nowa VALUES (1, 1)
INSERT INTO Nowa VALUES (1, 2)
INSERT INTO Nowa VALUES (2, 1)
INSERT INTO Nowa VALUES (2, 2)
INSERT INTO Nowa VALUES (1, 2)
INSERT INTO Nowa(nr1) VALUES (3)
INSERT INTO Nowa(nr2) VALUES (4)
INSERT INTO Nowa(nr2) VALUES (5)

SELECT * FROM Nowa