--DROP VIEW DaneV
GO
/*CREATE OR ALTER VIEW DaneV
AS
SELECT Nazwisko, Imie, RokUrodz
FROM Osoby
WHERE RokUrodz>1999
WITH CHECK OPTION
GO
INSERT INTO DaneV VALUES ('Król', 'Jan', 2005)
INSERT INTO DaneV VALUES ('Królik', 'January', 1995)
UPDATE DaneV SET RokUrodz=1993 WHERE RokUrodz=2005

SELECT * FROM DaneV
SELECT * FROM Osoby*/

/*CREATE OR ALTER VIEW DaneV1 (NazwiskoPrac, ImiePrac, kolumna)
AS
SELECT UPPER(Nazwisko) AS Nazwisko, Imie, RokUrodz*Wzrost AS kolumna
FROM Osoby



GO
INSERT INTO DaneV1 VALUES ('Królik', 'Janusz')
SELECT * FROM DaneV1
DROP VIEW DaneV1*/


SELECT * FROM sys.objects
SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM INFORMATION_SCHEMA.VIEWS
SELECT * FROM INFORMATION_SCHEMA.ROUTINES
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
