CREATE OR ALTER TRIGGER Sprawdz
ON Osoby
AFTER INSERT, UPDATE, DELETE
AS
SELECT * FROM INSERTED
SELECT * FROM DELETED

GO
INSERT INTO Osoby( Nazwisko) VALUES ('Lisowski')

UPDATE Osoby SET Nazwisko=LOWER( Nazwisko) WHERE IdOsoby>222

DELETE FROM Osoby WHERE IdOsoby>5000