--SELECT * FROM sys.trigger_event_types
DROP TRIGGER DlaDB ON DATABASE
GO
CREATE OR ALTER TRIGGER DlaDB
ON DATABASE
FOR --DDL_EVENTS
DDL_DATABASE_LEVEL_EVENTS
--DDL_TABLE_VIEW_EVENTS
--DDL_TABLE_EVENTS
--CREATE_TABLE, DROP_TABLE
AS
PRINT 'Modyfikacja schematu'

GO
CREATE TABLE xxx (id int)
ALTER TABLE xxx ADD opis varchar(2)
GO
CREATE VIEW xzx AS SELECT * FROM xxx
GO
CREATE PROCEDURE xzz AS SELECT * FROM xxx
GO
DROP PROCEDURE xzz
DROP VIEW xzx
DROP TABLE xxx