CREATE OR ALTER TRIGGER Zamiast
ON Osoby
INSTEAD OF DELETE 
AS
DECLARE @ile int
SELECT @ile=COUNT(*) FROM Zarobki WHERE IdOsoby IN (SELECT IdOsoby FROM DELETED)
IF @Ile>0
	PRINT 'Zakaz kasowania'
ELSE
	BEGIN
	PRINT 'Kasujê'
	DELETE FROM Osoby WHERE IdOsoby IN (SELECT IdOsoby FROM DELETED)
	END


GO
DELETE FROM Zarobki WHERE IdOsoby>5000
DELETE FROM Osoby WHERE IdOsoby>5000

SELECT * FROM Osoby

SELECT * FROM Zarobki