-- 1.1
USE [master]
GO
CREATE LOGIN [U2026a] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

-- 1.2
CREATE DATABASE [B2026a]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'B2026a', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\B2026a.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'B2026a_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\B2026a_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [B2026a] SET COMPATIBILITY_LEVEL = 170
GO
ALTER DATABASE [B2026a] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [B2026a] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [B2026a] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [B2026a] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [B2026a] SET ARITHABORT OFF 
GO
ALTER DATABASE [B2026a] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [B2026a] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [B2026a] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [B2026a] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [B2026a] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [B2026a] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [B2026a] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [B2026a] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [B2026a] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [B2026a] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [B2026a] SET  DISABLE_BROKER 
GO
ALTER DATABASE [B2026a] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [B2026a] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [B2026a] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [B2026a] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [B2026a] SET  READ_WRITE 
GO
ALTER DATABASE [B2026a] SET RECOVERY FULL 
GO
ALTER DATABASE [B2026a] SET  MULTI_USER 
GO
ALTER DATABASE [B2026a] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [B2026a] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [B2026a] SET DELAYED_DURABILITY = DISABLED 
GO
USE [B2026a]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [B2026a] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

-- 1.3
USE [B2026a]
GO
CREATE USER [U2026a] FOR LOGIN [U2026a]
GO
use [B2026a]
GO
GRANT BACKUP DATABASE TO [U2026a]
GO
use [B2026a]
GO
GRANT BACKUP LOG TO [U2026a]
GO

-- 2.1
USE [master]
GO
EXEC master.dbo.sp_addumpdevice  @devtype = N'disk', @logicalname = N'251190', @physicalname = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\Backup\251190.bak'
GO

-- 2.2
EXECUTE AS LOGIN='U2026a';
GO

-- Full1
BACKUP DATABASE [B2026a] TO  [251190] WITH FORMAT, INIT,  NAME = N'Full1', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- Diff1
BACKUP DATABASE [B2026a] TO  [251190] WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'Diff1', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- Log1
BACKUP LOG [B2026a] TO  [251190] WITH NOFORMAT, NOINIT,  NAME = N'Log1', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- Diff2
BACKUP DATABASE [B2026a] TO  [251190] WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'Diff2', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- Diff3
BACKUP DATABASE [B2026a] TO  [251190] WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'Diff3', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- Log2
BACKUP LOG [B2026a] TO  [251190] WITH NOFORMAT, NOINIT,  NAME = N'Log2', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- Log3
BACKUP LOG [B2026a] TO  [251190] WITH NOFORMAT, NOINIT,  NAME = N'Log3', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

REVERT;
GO

PRINT SUSER_NAME();

-- 3.1
USE [master]
RESTORE DATABASE [251190] FROM  [251190] WITH  FILE = 1,  MOVE N'B2026a' TO N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\251190.mdf',  MOVE N'B2026a_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\251190_log.ldf',  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE DATABASE [251190] FROM  [251190] WITH  FILE = 5,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [251190] FROM  [251190] WITH  FILE = 6,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [251190] FROM  [251190] WITH  FILE = 7,  NOUNLOAD,  STATS = 5

GO

-- 4.1
USE [master]
GO

GO
ALTER DATABASE [B2026a] ADD FILEGROUP [KOLO1]
GO


-- 4.2
USE [master]
GO

GO
ALTER DATABASE [B2026a] ADD FILE ( NAME = N'B01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\B01.ndf' , SIZE = 204800KB , FILEGROWTH = 65536KB ) TO FILEGROUP [KOLO1]
GO
ALTER DATABASE [B2026a] ADD FILE ( NAME = N'B02', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\B02.ndf' , SIZE = 204800KB , FILEGROWTH = 65536KB ) TO FILEGROUP [KOLO1]
GO

-- 4.3
USE [B2026a]
GO
CREATE TABLE TAB2026 (
    ID INT IDENTITY(1,1),
    DATA VARCHAR(100)
) ON KOLO1;
GO

-- 4.4
INSERT INTO TAB2026 (DATA) VALUES ('ZDAM TO KOLOKWIUM!!!');
GO 100

-- 4.5
USE [B2026a]
GO
DBCC SHRINKFILE (N'B01' , EMPTYFILE)
GO

-- 4.6
USE [B2026a]
GO
ALTER DATABASE [B2026a]  REMOVE FILE [B01]
GO

-- 4.7
USE [B2026a]
GO
DBCC SHRINKFILE (N'B02' , 24)
GO

-- 5.1
USE [north]
GO
CREATE USER [U2026a] FOR LOGIN [U2026a]
GO

-- 5.2
USE [north]
GO
CREATE ROLE [ROLA3] AUTHORIZATION [U2026a]
GO
CREATE ROLE [ROLA4] AUTHORIZATION [U2026a]
GO

-- 5.3
use [north]
GO
GRANT INSERT ON [dbo].[Categories] TO [ROLA3]
GO
use [north]
GO
GRANT SELECT ON [dbo].[Categories] TO [ROLA3]
GO
use [north]
GO
GRANT UPDATE ON [dbo].[Categories] TO [ROLA3]
GO
use [north]
GO
GRANT SELECT ON [dbo].[Products] TO [ROLA3]
GO
use [north]
GO
GRANT UPDATE ON [dbo].[Products] TO [ROLA3]
GO

-- 5.4
use [north]
GO
DENY INSERT ON [dbo].[Products] TO [ROLA4]
GO
use [north]
GO
DENY SELECT ON [dbo].[Products] TO [ROLA4]
GO

-- 5.5
use [north]
GO
DENY INSERT ON [dbo].[Categories] TO [ROLA4]
GO

-- 5.6
USE [north]
GO
ALTER ROLE [ROLA3] ADD MEMBER [U2026a]
GO
USE [north]
GO
ALTER ROLE [ROLA4] ADD MEMBER [U2026a]
GO

-- 5.7
EXECUTE AS USER = 'U2026a';
GO
SELECT * FROM fn_my_permissions('dbo.Categories', 'OBJECT');
GO
REVERT;
GO


-- 6.0 (TEGO BRAKOWAŁO) Tworzymy grupy plików i pliki
ALTER DATABASE B2026a ADD FILEGROUP GR1;
ALTER DATABASE B2026a ADD FILEGROUP GR2;
ALTER DATABASE B2026a ADD FILEGROUP GR3;
GO

-- Dodajemy pliki do grup (ścieżki przykładowe)
ALTER DATABASE B2026a ADD FILE (NAME = 'F1', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\F1.ndf') TO FILEGROUP GR1;
ALTER DATABASE B2026a ADD FILE (NAME = 'F2', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\F2.ndf') TO FILEGROUP GR2;
ALTER DATABASE B2026a ADD FILE (NAME = 'F3', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\F3.ndf') TO FILEGROUP GR3;
GO

-- 6.1

USE B2026a;
GO
CREATE PARTITION FUNCTION PF2026 (date)
AS RANGE LEFT FOR VALUES ('2023-01-01', '2026-01-01');
GO

-- 6.2
CREATE PARTITION SCHEME PS2026
AS PARTITION PF2026
TO (GR1, GR2, GR3);
GO

-- 6.3
CREATE TABLE TEST (ID INT IDENTITY(1,1), ROK DATE)
ON PS2026(ROK);
GO

-- 6.4
ALTER PARTITION SCHEME PS2026 NEXT USED GR3;
GO

-- 6.5
ALTER PARTITION FUNCTION PF2026() SPLIT RANGE ('2027-01-01');
GO

-- 6.6
INSERT INTO TEST (ROK) VALUES ('2020-01-01');
GO 10
INSERT INTO TEST (ROK) VALUES ('2024-01-01');
GO 10
INSERT INTO TEST (ROK) VALUES ('2026-06-01');
GO 10
INSERT INTO TEST (ROK) VALUES ('2028-01-01');
GO 10
